"""Add missing tables

Revision ID: 4e4f4b511b0e
Revises: f9171faa3212
Create Date: 2026-05-06 23:13:28.887595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e4f4b511b0e'
down_revision: Union[str, Sequence[str], None] = 'f9171faa3212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table: str, column: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return column in {c["name"] for c in inspector.get_columns(table)}


def _table_exists(table: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return table in inspector.get_table_names()


def _index_exists(table: str, index: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return index in {i["name"] for i in inspector.get_indexes(table)}


def _ensure_token_blacklist() -> None:
    """Create ``token_blacklist`` if absent.

    No migration in the chain ever created this table (it only existed on the
    legacy DB), yet both this migration and m12_add_missing_timestamps alter it.
    Mirror the ``TokenBlacklist`` model so fresh deployments get the table.
    """
    if _table_exists("token_blacklist"):
        return
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(255), nullable=False),
        sa.Column("invalidated_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_token_blacklist_user_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_token_blacklist_token_hash", "token_blacklist", ["token_hash"], unique=True)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_member_id'), 'team_members', ['member_id'], unique=False)
    op.create_index(op.f('ix_team_members_owner_id'), 'team_members', ['owner_id'], unique=False)
    # The ``source`` column is added later (m17_add_missing_application_columns);
    # on a fresh DB it does not exist yet, so the index must wait for that column.
    if _column_exists('applications', 'source'):
        op.create_index(op.f('ix_applications_source'), 'applications', ['source'], unique=False)
    _ensure_token_blacklist()
    # Legacy index that only exists on databases predating the rename.
    if _index_exists('token_blacklist', 'token_hash') and not _index_exists('token_blacklist', 'ix_token_blacklist_token_hash'):
        op.drop_index(op.f('token_hash'), table_name='token_blacklist')
    if not _index_exists('token_blacklist', 'ix_token_blacklist_expires_at'):
        op.create_index(op.f('ix_token_blacklist_expires_at'), 'token_blacklist', ['expires_at'], unique=False)
    if not _index_exists('token_blacklist', 'ix_token_blacklist_id'):
        op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    if not _index_exists('token_blacklist', 'ix_token_blacklist_token_hash'):
        op.create_index(op.f('ix_token_blacklist_token_hash'), 'token_blacklist', ['token_hash'], unique=True)
    if not _index_exists('token_blacklist', 'ix_token_blacklist_user_id'):
        op.create_index(op.f('ix_token_blacklist_user_id'), 'token_blacklist', ['user_id'], unique=False)
    fks = {f["referred_table"] for f in sa.inspect(op.get_bind()).get_foreign_keys('token_blacklist')}
    if "users" not in fks:
        op.create_foreign_key("fk_token_blacklist_user_id", 'token_blacklist', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint("fk_token_blacklist_user_id", 'token_blacklist', type_='foreignkey')
    except Exception:
        pass
    op.drop_index(op.f('ix_token_blacklist_user_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_token_hash'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_expires_at'), table_name='token_blacklist')
    op.create_index(op.f('token_hash'), 'token_blacklist', ['token_hash'], unique=True)
    op.drop_index(op.f('ix_applications_source'), table_name='applications')
    op.drop_index(op.f('ix_team_members_owner_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_member_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
