"""sync_legacy_schema

Revision ID: 6e4cadea7e92
Revises: 367fd943df54
Create Date: 2026-05-01 18:11:16.610708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e4cadea7e92'
down_revision: Union[str, Sequence[str], None] = '367fd943df54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _applications_columns():
    """Live column names on ``applications`` at migration time.

    This legacy schema-sync migration must be tolerant of columns that later
    migrations in the chain drop (``calibration_json``/``calibration_verified_skills``
    are dropped by m16_drop_deprecated_interview_state_columns) or columns the
    model declares but no other migration ever adds (``evaluation_state`` &
    friends — present on the live DB only via ``create_all`` drift). Guarding on
    live column existence keeps brand-new deployments from failing with
    ``Unknown column '...'`` at this step.
    """
    inspector = sa.inspect(op.get_bind())
    return {c["name"] for c in inspector.get_columns("applications")}


def upgrade() -> None:
    """Upgrade schema."""
    cols = _applications_columns()
    # ### commands auto generated by Alembic - please adjust! ###
    # Missing model columns: the Application model declares these but no other
    # migration adds them, so a fresh DB would lack them until a later integrity
    # migration (p1prod202606111615) reads/constrains them.
    if "evaluation_state" not in cols:
        op.add_column('applications', sa.Column('evaluation_state', sa.String(20), nullable=True))
    if "evaluation_completed_at" not in cols:
        op.add_column('applications', sa.Column('evaluation_completed_at', sa.DateTime(), nullable=True))
    if "evaluation_source" not in cols:
        op.add_column('applications', sa.Column('evaluation_source', sa.String(20), nullable=True))
    cols = _applications_columns()
    if "calibration_json" in cols:
        op.alter_column('applications', 'calibration_json',
                   existing_type=mysql.LONGTEXT(),
                   type_=sa.Text(),
                   existing_nullable=True)
    if "calibration_verified_skills" in cols:
        op.alter_column('applications', 'calibration_verified_skills',
                   existing_type=mysql.LONGTEXT(),
                   type_=sa.Text(),
                   existing_nullable=True)
    op.create_index('idx_applications_assigned_status', 'applications', ['assigned_to', 'status'], unique=False)
    op.create_index('idx_applications_batch_status', 'applications', ['batch_id', 'status'], unique=False)
    op.create_index('idx_applications_interview_state', 'applications', ['interview_state', 'updated_at'], unique=False)
    if "evaluation_state" in cols:
        op.create_index(op.f('ix_applications_evaluation_state'), 'applications', ['evaluation_state'], unique=False)
    op.create_index('idx_login_attempts_email_timestamp', 'login_attempts', ['email', 'timestamp'], unique=False)
    op.create_index('idx_login_attempts_ip_timestamp', 'login_attempts', ['ip_address', 'timestamp'], unique=False)
    op.add_column('users', sa.Column('temp_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    cols = _applications_columns()
    try:
        op.drop_column('users', 'temp_password')
    except Exception:
        pass
    op.drop_index('idx_login_attempts_ip_timestamp', table_name='login_attempts')
    op.drop_index('idx_login_attempts_email_timestamp', table_name='login_attempts')
    op.drop_index(op.f('ix_applications_evaluation_state'), table_name='applications')
    op.drop_index('idx_applications_interview_state', table_name='applications')
    op.drop_index('idx_applications_batch_status', table_name='applications')
    op.drop_index('idx_applications_assigned_status', table_name='applications')
    if "calibration_verified_skills" in cols:
        op.alter_column('applications', 'calibration_verified_skills',
                   existing_type=sa.Text(),
                   type_=mysql.LONGTEXT(),
                   existing_nullable=True)
    if "calibration_json" in cols:
        op.alter_column('applications', 'calibration_json',
                   existing_type=sa.Text(),
                   type_=mysql.LONGTEXT(),
                   existing_nullable=True)
    if "evaluation_source" in cols:
        op.drop_column('applications', 'evaluation_source')
    if "evaluation_completed_at" in cols:
        op.drop_column('applications', 'evaluation_completed_at')
    if "evaluation_state" in cols:
        op.drop_column('applications', 'evaluation_state')
    # ### end Alembic commands ###
