"""add_otp_code_to_email_verification

Revision ID: f9171faa3212
Revises: 91e28cea7dce
Create Date: 2026-05-04 10:24:22.036570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9171faa3212'
down_revision: Union[str, Sequence[str], None] = '91e28cea7dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verifications', sa.Column('code', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_verifications', 'code')
    # ### end Alembic commands ###
